Module2 task1
htmlacademy-ecmascript/1053261-big-trip-14 pull request #6
Opened 2021-06-26 06:11 UTC by mihan007

2021-06-26 09:34 UTC, balesniy requested changes
- с шаблонами все отлично
- в данных немного не попали с опциями, для отладки шаблонов это не принципиально, но потом придется переделать. тип точки определяет список возможных опций, а сама точка хранит список выбранных.
- по коду мне очень понравилось использование символов для типов
- хочется единообразия в объявлении функций, мы все можем описать стрелочными, и выражение сильно удобнее типизировать
- у тебя хорошие чистые функции объявлены внутри других функций, их можно выносить (как и константы), тогда и код читать легче, и они не создаются снова при вызове. на скорость это не влияет, но все оптимизации в том же реакте построены на ссылочном равенстве, а для этого функции должны сохранятся между вызовами

2021-06-26 09:34 UTC, balesniy commented on src/view/point-list.js
> +  const durationTemplate = duration.hours() > 0
в тз еще просят выделить дни

2021-06-26 09:34 UTC, balesniy commented on src/view/point-form.js
> +  const pointTypeNameTemplate = typeName ? typeName : PointTypeNames[type];
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator

2021-06-26 09:34 UTC, balesniy commented on src/view/point-form.js
> +    `<option value="Amsterdam" ${currentDestination && currentDestination.title === destinationName ? 'selected' : ''}></option>`;
value пропустил

2021-06-26 09:34 UTC, balesniy commented on src/view/point-form.js
> +  for (const offerTitle of PointTypeOffers[type]) {
for+push можно заменить на map

2021-06-26 09:34 UTC, balesniy commented on src/view/point-form.js
> +      price: getRandomInteger(OfferPriceRange.min, OfferPriceRange.max),
цена предложения придет с сервера, сейчас ее можно взять из "справочника"

2021-06-26 09:34 UTC, balesniy commented on src/view/point-form.js
> +      if (currentOffer.title === offerTitle) {
для массива можно что то готовое взять, includes или find

2021-07-01 04:18 UTC, mihan007 commented on src/view/info.js
> +    if (pointTitle !== lastAddedTitle) {
тут идея в том, чтобы смерджить соседние точки, если они в одном городе. то есть если у нас в последовательности событий есть такси в Москве, а за ним ресторан в Москве - нам надо Москву один раз добавить в маршрут

2021-07-01 05:53 UTC, mihan007 commented
@balesniy все поправил. из интересного
1. Избавился от for в пользу Array.map и небольшую функцию range сделал, которая отдает численный массив
2. Nullish coalescing operator потребовал подключить babel вместе с https://babeljs.io/docs/en/babel-plugin-proposal-nullish-coalescing-operator

2021-07-01 07:07 UTC, balesniy approved these changes
мне все нравится, осталось несколько мелочей по стилю, из интересного только маршрут в случае наложения событий, но это скорее к тз вопросы. так что моки готовы, шаблоны готовы, можно двигаться дальше

2021-07-01 07:31 UTC, merged